# -*- coding: utf-8 -*-
"""233005422e_CSE_443_Problem_Set_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvkqKI28BusPNKOaXmRJ94nDicy9y7C_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load data (semicolon separator)
df = pd.read_csv('bank-full.csv', sep=';')

# Display basic info
print(df.info())
print(df.head())
print(df['y'].value_counts(normalize=True))

# Check missing values (encoded as 'unknown')
for col in df.select_dtypes(include='object').columns:
    print(f"{col}: {df[col].value_counts(normalize=True).get('unknown', 0)*100:.1f}% unknown")

# Visualize target distribution
sns.countplot(x='y', data=df)
plt.title('Term Deposit Subscription')
plt.show()

# Numerical features distribution
num_cols = ['age', 'balance', 'duration', 'campaign', 'pdays', 'previous']
df[num_cols].hist(bins=30, figsize=(12,8))
plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve

# Separate features and target
X = df.drop('y', axis=1)
y = df['y'].map({'yes': 1, 'no': 0})   # binary encoding

# Define column types
cat_cols = X.select_dtypes(include='object').columns.tolist()
num_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Create preprocessor
preprocessor = ColumnTransformer([
    ('num', StandardScaler(), num_cols),
    ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), cat_cols)
])

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Build pipeline
log_reg = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', log_reg)])

# Train the model
pipeline.fit(X_train, y_train)

# Predictions
y_pred = pipeline.predict(X_test)
y_proba = pipeline.predict_proba(X_test)[:, 1]

# Classification metrics
print(classification_report(y_test, y_pred, target_names=['no', 'yes']))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

# ROC-AUC
auc = roc_auc_score(y_test, y_proba)
print(f"ROC-AUC Score: {auc:.3f}")

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_proba)
plt.plot(fpr, tpr, label=f'Logistic Regression (AUC = {auc:.3f})')
plt.plot([0,1], [0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.legend()
plt.show()

# Get feature names after one-hot encoding
cat_features = pipeline.named_steps['preprocessor'].named_transformers_['cat'].get_feature_names_out(cat_cols)
all_features = num_cols + list(cat_features)

# Coefficients
coefs = pipeline.named_steps['classifier'].coef_[0]

# Create DataFrame
importance = pd.DataFrame({'feature': all_features, 'coefficient': coefs})
importance = importance.sort_values(by='coefficient', key=abs, ascending=False)

# Plot top 10 positive and negative coefficients
top10 = importance.head(10)
plt.figure(figsize=(8,6))
sns.barplot(x='coefficient', y='feature', data=top10, palette='coolwarm')
plt.title('Top 10 Most Influential Features')
plt.tight_layout()
plt.show()

from sklearn.model_selection import GridSearchCV

param_grid = {
    'classifier__C': [0.01, 0.1, 1, 10],
    'classifier__penalty': ['l2'],
    'classifier__solver': ['lbfgs']
}

grid = GridSearchCV(pipeline, param_grid, cv=5, scoring='roc_auc', n_jobs=-1)
grid.fit(X_train, y_train)

print("Best parameters:", grid.best_params_)
print("Best ROC-AUC (CV):", grid.best_score_)

# Example new customer data (as a DataFrame)
new_customer = pd.DataFrame([{
    'age': 35, 'job': 'management', 'marital': 'married', 'education': 'tertiary',
    'default': 'no', 'balance': 1500, 'housing': 'yes', 'loan': 'no',
    'contact': 'cellular', 'day': 15, 'month': 'jun', 'duration': 200,
    'campaign': 1, 'pdays': 10, 'previous': 1, 'poutcome': 'success'
}])

# Predict probability
prob = pipeline.predict_proba(new_customer)[0, 1]
print(f"Probability of subscribing: {prob:.2f}")